symbol/symbol-openapi

spec/openapi3.yaml
Closes https://github.com/nemtech/nem2-docs/issues/231, based on https://stackoverflow.com/questions/32971216/request-body-with-optional-property
=> Fixed optional account ids

spec/openapi3.yaml
The endpoints wrap the array response in an object named ``accountNames``.
Related: https://github.com/nemtech/nem2-sdk-java/issues/72
=> Fixed names response

spec/openapi3.yaml
EmbeddedTransactionMetaDTO was using and old TransactionMetaDTO definition.
=> Split TransactionMetaDTO

spec/openapi3.yaml
=> Fixed Mosaic Restriction transaction names differ from Catbuffer

spec/openapi3.yaml
=> Fixed NamespaceNameDTO key name (namespaceId) mismatch

spec/openapi3.yaml
=> Updated metadata endpoint

spec/openapi3.yaml
https://github.com/nemtech/catapult-rest/issues/150
=> Added metadata hex

spec/openapi3.yaml
=> HaskLockTranscation mosaic object vs mosaicId/Value

spec/openapi3.yaml
=> 38 metadata value size

spec/openapi3.yaml
=> Added message types

spec/openapi3.yaml
=> Added network type name enum

spec/openapi3.yaml
Proposal for https://github.com/nemtech/catapult-rest/issues/11
=> Proposed mosaic owned endpoints

_build/openapi3.yml, _build/postman.json, spec/core/network/schemas/NetworkTypeDTO.yml, spec/core/network/schemas/NetworkTypeNameEnum.yml, spec/plugins/aggregate/routes/announceCosignatureTransaction.yml, spec/plugins/aggregate/routes/announcePartialTransaction.yml, spec/schemas.yml, spec/tags.yml
Removed NetworkTypeNameEnum
Removed Aggreagate Route
=> F2 improvements

spec/core/account/routes/getAccountConfirmedTransactions.yml, spec/core/account/routes/getAccountIncomingTransactions.yml, spec/core/account/routes/getAccountOutgoingTransactions.yml, spec/core/account/routes/getAccountPartialTransactions.yml, spec/core/account/routes/getAccountUnconfirmedTransactions.yml, spec/parameters/_index.yml, spec/parameters/transactionType.yml, spec/routes.yml
=> Added filter tx by type

spec/parameters/height.yml, spec/parameters/limit.yml
=> Removed page size step

spec/core/node/routes/getNodePeers.yml, spec/routes.yml
=> Document node peers

spec/core/transaction/schemas/EmbeddedTransactionDTO.yml
=> Removed TransactionBodyDTO from EmbeddedTransactionDTO

spec/parameters/transactionTypes.yml
Related https://github.com/nemtech/catapult-rest/issues/270
=> Changed explode to true

spec/core/account/routes/getAccountPartialTransactions.yml
Reported in https://github.com/nemtech/catapult-rest/issues/244
=> Fix partial description

spec/core/block/routes/getBlockTransactions.yml
Temporal fix for https://github.com/nemtech/catapult-rest/issues/283
=> Remove ordering from getBlockTransactions

.travis.yml, CHANGELOG.md, package-lock.json, package.json, spec/core/account/routes/getAccountPartialTransactions.yml, spec/core/block/routes/getBlockTransactions.yml, spec/info.yml, spec/parameters/_index.yml, travis/github-pages.sh, travis/release.sh
Merge from master to release branch.
Test to check if the automation script works
=> New release 0.8.9

spec/core/account/schemas/AccountDTO.yml, spec/core/account/schemas/AccountKeyDTO.yml, spec/core/account/schemas/KeyTypeEnum.yml, spec/schemas/_index.yml
- Added supplementalAccountKeys
Fixed #121
=> SupplementalAccountKeys in account info

spec/core/network/schemas/NetworkPropertiesDTO.yml
=> GenerationHashSeed in network properties

spec/core/node/schemas/NodeInfoDTO.yml, spec/plugins/mosaic/schemas/MosaicDefinitionTransactionBodyDTO.yml
- renamed to networkGenerationHashSeed
Fixed #131
=> Renamed to networkGenerationHashSeed

spec/plugins/account_link/schemas/AccountKeyLinkTransactionBodyDTO.yml
=> Fixed linked public key

spec/core/transaction/schemas/TransactionStatusTypeEnum.yml
=> Update 095 errors

.gitignore, spec/core/transaction/routes/getTransaction.yml, spec/core/transaction/schemas/TransactionInfoExtendedDTO.yml
Fixes https://github.com/nemtech/symbol-openapi/issues/144
Note: this is not the fix of top-level id location, it's just allowing top-level entities to be embedded
=> Allowing aggregate meta at top level transaction endpoints

spec/core/block/schemas/BlockInfoDTO.yml
=> BlockInfo.id should be required

spec/core/network/schemas/ChainPropertiesDTO.yml, spec/core/network/schemas/NetworkPropertiesDTO.yml, spec/plugins/mosaic/schemas/MosaicNetworkPropertiesDTO.yml, spec/plugins/namespace/schemas/NamespaceNetworkPropertiesDTO.yml
=> Updated network properties

spec/core/account/schemas/AccountDTO.yml
=> Renamed AccountKeys to AccountPublicKeys

spec/core/account/schemas/AccountDTO.yml, spec/core/account/schemas/AccountKeyDTO.yml, spec/core/account/schemas/AccountLinkPublicKeyDTO.yml, spec/core/account/schemas/AccountLinkVotingKeyDTO.yml, spec/core/account/schemas/AccountLinkVotingKeysDTO.yml, spec/core/account/schemas/SupplementalPublicKeysDTO.yml, spec/schemas/_index.yml
=> SupplementalPublicKeys

spec/core/network/schemas/ChainPropertiesDTO.yml, spec/core/transaction/schemas/TransactionStatusEnum.yml
=> Added new status and chain properties

spec/schemas/Pagination.yml
=> Removed totalEntries and totalPages from pagination

.travis.yml, package-lock.json, package.json, spec/schemas/_index.yml
Plus fixing some missing imports.
=> Npm local modules

spec/plugins/lock_hash/routes/getHashLock.yml, spec/plugins/lock_hash/routes/searchHashLock.yml, spec/plugins/lock_secret/routes/getSecretLock.yml, spec/plugins/lock_secret/routes/searchSecretLock.yml, spec/routes.yml, spec/tags.yml
Routes and methods are returning HashLock/SecretLock objects,  they should use those terms
https://github.com/nemtech/symbol-openapi/issues/203
=> Hash Lock and Secret Lock routes and methods

spec/core/node/schemas/RolesTypeEnum.yml, spec/schemas/_index.yml
Fixes https://github.com/nemtech/symbol-openapi/issues/208
but without the array improvement. The array of roles would be presented in the SDKs.
=> Added voting node role

spec/core/transaction/routes/searchConfirmedTransactions.yml, spec/core/transaction/routes/searchPartialTransactions.yml, spec/core/transaction/routes/searchUnconfirmedTransactions.yml, spec/parameters/_index.yml, spec/parameters/query/fromHeight.yml, spec/parameters/query/toHeight.yml
Closes https://github.com/nemtech/catapult-rest/issues/469
=> Added from/to height query filters to the transaction search endpoints

spec/info.yml
=> version in info.yml

spec/core/block/schemas/BlockMetaDTO.yml
Fixes https://github.com/nemtech/symbol-openapi/issues/221
=> Updated Block Meta

spec/core/transaction/routes/searchConfirmedTransactions.yml, spec/core/transaction/routes/searchPartialTransactions.yml, spec/core/transaction/routes/searchUnconfirmedTransactions.yml, spec/parameters/_index.yml, spec/parameters/query/transferMosaicId.yml
=> Added transactions transferMosaicId filter

spec/core/transaction/routes/searchConfirmedTransactions.yml
regarding this: https://github.com/nemtech/catapult-rest/issues/442
=> Improved search transactions endpoint description regarding alias resolution and addresses

spec/core/node/routes/getUnlockedAccount.yml, spec/core/node/schemas/UnlockedAccountDTO.yml, spec/routes.yml, spec/schemas/_index.yml
added unlocked account endpoint
=> unlocked account

spec/core/transaction/schemas/TransactionStatusEnum.yml
case 0x80FF0005: return 'Failure_Chain_Block_Invalid_Vrf_Proof';
case 0x80FF0006: return 'Failure_Chain_Block_Unknown_Signer';
=> Added missing failure status

spec/core/entity/schemas/NetworkTypeEnum.yml
Fixes https://github.com/nemtech/symbol-openapi/issues/256
=> Updated network types

spec/parameters/query/embedded.yml
It does not combine well with address filtering.
=> Clarify search of embedded transactions

spec/core/node/schemas/DeploymentDTO.yml, spec/core/node/schemas/ServerDTO.yml, spec/schemas/_index.yml
Example:
http://ngl-dual-101.testnet.symboldev.network:3000/node/server
Fixes https://github.com/nemtech/symbol-openapi/issues/274
=> feat: added deployment data to /node/server.

spec/plugins/receipt/schemas/ResolutionStatementInfoDTO.yml, spec/plugins/receipt/schemas/StatementMetaDTO.yml, spec/plugins/receipt/schemas/TransactionStatementInfoDTO.yml, spec/schemas/Timestamp.yml, spec/schemas/_index.yml
fix: Fixed and improved timestamp description.
Open API of rest PR https://github.com/symbol/catapult-rest/pull/647
Fixes https://github.com/symbol/symbol-openapi/issues/279
=> feat: Added meta to transaction and resolution statements.

spec/core/transaction/schemas/EmbeddedTransactionMetaDTO.yml, spec/core/transaction/schemas/TransactionMetaDTO.yml
Open api of https://github.com/symbol/catapult-rest/pull/658
=> feat: Added feeMultiplier and timestamp to transaction's meta

spec/openapi.yml
This page does not exist anymore.
=> Update the main documentation page link

CHANGELOG.md, spec/plugins/mosaic/schemas/EmbeddedMosaicSupplyRevocationTransactionDTO.yml, spec/plugins/mosaic/schemas/MosaicFlagsEnum.yml, spec/plugins/mosaic/schemas/MosaicSupplyRevocationTransactionBodyDTO.yml, spec/plugins/mosaic/schemas/MosaicSupplyRevocationTransactionDTO.yml, spec/schemas/_index.yml
Open api spec of the new revoke transaction and flag
https://github.com/symbol/catapult-rest/pull/672
=> feat: Added mosaic supply revocation support.

spec/core/transaction/schemas/EmbeddedTransactionInfoDTO.yml, spec/core/transaction/schemas/TransactionInfoDTO.yml, spec/core/transaction/schemas/TransactionTypeEnum.yml
Missing the reference in the anyOf fo transaction body
=> fix: Added missing supply revocation transaction to transaction info
